#!/usr/bin/env python3
"""Apply youtube-pod's local patches to the bundled Python packages.

`scripts/bootstrap.sh` reinstalls `PythonRuntime/site-packages` from
`PythonRuntime/requirements.lock` (with `--upgrade`), so any fix to a vendored
package has to be re-applied after every install. This script is that step.
It is idempotent: already patched files are left alone, pristine upstream
files are patched, and anything else (a partially patched file or an upstream
version whose text no longer matches) fails loudly instead of being skipped.

Patches (see PythonRuntime/patches/README.md for the background):

1. yt-dlp-apple-webkit-jsi: add `webView:decidePolicyForNavigationAction:decisionHandler:`
   to the hidden WKWebView's navigation delegate so script-initiated navigations
   are cancelled instead of being handed to iOS as Universal Links.
2. yt-dlp-ejs: only assign `globalThis.location` when it is undefined, so the
   solver's synthetic YouTube location never becomes a real navigation inside a
   browser-backed runtime. yt-dlp verifies the solver scripts by SHA3-512, so the
   two affected digests in yt-dlp's vendored `_info.py` are recomputed from the
   patched files.

Usage:
    python3 scripts/patch_python_runtime.py          # apply (idempotent)
    python3 scripts/patch_python_runtime.py --check  # verify only, no writes
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SITE_PACKAGES = PROJECT_ROOT / "PythonRuntime" / "site-packages"

# Pinned in PythonRuntime/requirements.lock. The anchors below were validated
# against exactly these versions; bumping the lock requires re-validating them.
EJS_VERSION = "0.8.0"
PLUGIN_VERSION = "0.1.1"

EJS_VERSION_FILE = "yt_dlp_ejs/_version.py"
PLUGIN_VERSION_FILE = "yt_dlp_plugins/extractor/webkit_jsi.py"
VENDOR_INFO_FILE = "yt_dlp/extractor/youtube/jsc/_builtin/vendor/_info.py"

# Digests shipped by yt-dlp 2026.08.19 for the unpatched ejs 0.8.0 core scripts.
# Used only to give a precise diagnostic when `_info.py` is still pristine.
UPSTREAM_CORE_HASHES = {
    "yt.solver.core.js": (
        "c163a6f376db6ce3da47d516a28a8f2a0554ae95c58dc766f0a6e2b3894f2cef"
        "1ee07fa84beb442fa471aac4f300985added1657c7c94c4d1cfefe68920ab599"
    ),
    "yt.solver.core.min.js": (
        "ee5b307d07f55e91e4723edf5ac205cc877a474187849d757dc1322e38427b15"
        "7a9d706d510c1723d3670f98e5a3f8cbcde77874a80406bd7204bc9fea30f283"
    ),
}

# Files whose digests appear in _info.py under the given keys.
CORE_SCRIPTS = {
    "yt.solver.core.min.js": "yt_dlp_ejs/yt/solver/core.min.js",
    "yt.solver.core.js": "yt_dlp/extractor/youtube/jsc/_builtin/vendor/yt.solver.core.js",
}

HASH_MARKER = "# youtube-pod: core script hashes rewritten by scripts/patch_python_runtime.py\n"
HASH_MARKER_ANCHOR = "# This file is generated by devscripts/update_requirements.py. DO NOT MODIFY!\n"


class PatchError(Exception):
    pass


@dataclass(frozen=True)
class Edit:
    anchor: str
    replacement: str


@dataclass(frozen=True)
class Patch:
    name: str
    path: str
    edits: tuple[Edit, ...]


# --- Patch 1: yt-dlp-apple-webkit-jsi navigation policy -----------------------

WEBKIT_JSI_API = "yt_dlp_plugins/webkit_jsi/lib/api.py"

_JSI_REGISTRY_ANCHOR = "        navi_cbdct: dict[int, Callable[[], None]] = {}\n"
_JSI_REGISTRY_REPLACEMENT = (
    _JSI_REGISTRY_ANCHOR
    + "        # youtube-pod patch: webviews whose next navigation was requested by\n"
    "        # navigate_to (loadHTMLString:baseURL:). Every other navigation is cancelled in\n"
    "        # webView:decidePolicyForNavigationAction:decisionHandler: so that script-initiated\n"
    "        # navigations (e.g. `globalThis.location = new URL(...)` in yt-dlp-ejs) never leave\n"
    "        # the process as Universal Links. See grqz/yt-dlp-apple-webkit-jsi#5.\n"
    "        navi_allowed_webviews: set[int] = set()\n"
    "        WK_NAVIGATION_ACTION_POLICY_CANCEL = 0\n"
    "        WK_NAVIGATION_ACTION_POLICY_ALLOW = 1\n"
)

_JSI_METHOD_ANCHOR = (
    "            @staticmethod\n"
    "            def userContentController0_didReceiveScriptMessage1("
)
_JSI_METHOD_REPLACEMENT = (
    "            @staticmethod\n"
    "            def webView0_decidePolicyForNavigationAction1_decisionHandler2(\n"
    "                this: CRet.Py_PVoid, sel: CRet.Py_PVoid,\n"
    "                rp_webview: CRet.Py_PVoid, rp_navaction: CRet.Py_PVoid, rp_decisionhandler: CRet.Py_PVoid\n"
    "            ) -> None:\n"
    "                # youtube-pod patch, see navi_allowed_webviews above.\n"
    "                policy = WK_NAVIGATION_ACTION_POLICY_CANCEL\n"
    "                url = '<unknown>'\n"
    "                try:\n"
    "                    if rp_navaction:\n"
    "                        rp_req = c_void_p(pa.send_message(c_void_p(rp_navaction), b'request', restype=c_void_p))\n"
    "                        if rp_req.value:\n"
    "                            rp_url = c_void_p(pa.send_message(rp_req, b'URL', restype=c_void_p))\n"
    "                            if rp_url.value:\n"
    "                                url = str_from_nsstring(pa, c_void_p(pa.send_message(\n"
    "                                    rp_url, b'absoluteString', restype=c_void_p)), default='<unknown>')\n"
    "                    if (rp_webview or 0) in navi_allowed_webviews:\n"
    "                        policy = WK_NAVIGATION_ACTION_POLICY_ALLOW\n"
    "                except Exception as e:\n"
    "                    pa.logger.warning(f'decidePolicyForNavigationAction: failed to inspect navigation, cancelling: {e!r}')\n"
    "                    policy = WK_NAVIGATION_ACTION_POLICY_CANCEL\n"
    "                pa.logger.trace(\n"
    "                    f'Callback: [(PyForeignClass_WebViewHandler){this} webView: {rp_webview} '\n"
    "                    f'decidePolicyForNavigationAction: {rp_navaction} ({url}) decisionHandler: {rp_decisionhandler}] '\n"
    "                    f'-> {\"allow\" if policy else \"cancel\"}')\n"
    "                if policy == WK_NAVIGATION_ACTION_POLICY_CANCEL:\n"
    "                    pa.logger.debug(f'Cancelled navigation to {url}')\n"
    "                decisionhandler = cast(rp_decisionhandler or 0, POINTER(ObjCBlock)).contents\n"
    "                decisionhandler.as_pycb(None, c_long)(policy)\n"
    "\n"
    + _JSI_METHOD_ANCHOR
)

_JSI_METH_LIST_ANCHOR = (
    "                b'v@:@@',\n"
    "            ), (\n"
    "                pa.sel_registerName(b'userContentController:didReceiveScriptMessage:'),\n"
)
_JSI_METH_LIST_REPLACEMENT = (
    "                b'v@:@@',\n"
    "            ), (\n"
    "                # youtube-pod patch\n"
    "                pa.sel_registerName(b'webView:decidePolicyForNavigationAction:decisionHandler:'),\n"
    "                CFUNCTYPE(\n"
    "                    None,\n"
    "                    c_void_p, c_void_p, c_void_p, c_void_p, c_void_p)(\n"
    "                        PFC_WVHandler.webView0_decidePolicyForNavigationAction1_decisionHandler2),\n"
    "                b'v@:@@@?',\n"
    "            ), (\n"
    "                pa.sel_registerName(b'userContentController:didReceiveScriptMessage:'),\n"
)

_JSI_NAVIGATE_ANCHOR = (
    "                        rp_navi = py_typecast(NotNull_VoidP, c_void_p(pa.send_message(\n"
    "                            c_void_p(webview), b'loadHTMLString:baseURL:', ps_html, purl_base,\n"
)
_JSI_NAVIGATE_REPLACEMENT = (
    "                        # youtube-pod patch: allow only this API-requested load.\n"
    "                        navi_allowed_webviews.add(webview)\n"
    "                        exsk.callback(navi_allowed_webviews.discard, webview)\n"
    + _JSI_NAVIGATE_ANCHOR
)

WEBKIT_JSI_PATCH = Patch(
    name="yt-dlp-apple-webkit-jsi: cancel script-initiated WKWebView navigations",
    path=WEBKIT_JSI_API,
    edits=(
        Edit(_JSI_REGISTRY_ANCHOR, _JSI_REGISTRY_REPLACEMENT),
        Edit(_JSI_METHOD_ANCHOR, _JSI_METHOD_REPLACEMENT),
        Edit(_JSI_METH_LIST_ANCHOR, _JSI_METH_LIST_REPLACEMENT),
        Edit(_JSI_NAVIGATE_ANCHOR, _JSI_NAVIGATE_REPLACEMENT),
    ),
)

# --- Patch 2: yt-dlp-ejs synthetic location guard ------------------------------

# The solver's environment bootstrap lives inside a JS string literal handed to
# meriyah.parse(...); its newlines are the two characters backslash + n.
_EJS_LOCATION_ANCHOR = (
    '} else {\\n'
    '    globalThis.location = new URL("https://www.youtube.com/watch?v=yt-dlp-wins");\\n'
    '}'
)
_EJS_LOCATION_REPLACEMENT = (
    '} else if (typeof globalThis.location === "undefined") {\\n'
    '    globalThis.location = new URL("https://www.youtube.com/watch?v=yt-dlp-wins");\\n'
    '}'
)

EJS_PATCHES = tuple(
    Patch(
        name=f"yt-dlp-ejs: guard globalThis.location assignment ({key})",
        path=path,
        edits=(Edit(_EJS_LOCATION_ANCHOR, _EJS_LOCATION_REPLACEMENT),),
    )
    for key, path in CORE_SCRIPTS.items()
)

ALL_PATCHES = (WEBKIT_JSI_PATCH, *EJS_PATCHES)


# --- Helpers -------------------------------------------------------------------

def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise PatchError(f"{path} is missing. Run ./scripts/bootstrap.sh first.") from None


def write_atomic(path: Path, text: str) -> None:
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    os.replace(temporary, path)


def sha3_512(path: Path) -> str:
    # Same recipe as yt_dlp.extractor.youtube.jsc._builtin.ejs.Script.hash.
    return hashlib.sha3_512(read(path).encode("utf-8")).hexdigest()


def check_versions() -> None:
    ejs = re.search(r"^__version__ = version = '([^']+)'$", read(SITE_PACKAGES / EJS_VERSION_FILE), re.M)
    plugin = re.search(r"^__version__ = '([^']+)'$", read(SITE_PACKAGES / PLUGIN_VERSION_FILE), re.M)
    found = {
        "yt-dlp-ejs": (ejs.group(1) if ejs else None, EJS_VERSION),
        "yt-dlp-apple-webkit-jsi": (plugin.group(1) if plugin else None, PLUGIN_VERSION),
    }
    mismatches = [f"{name}: found {actual!r}, patches validated against {expected!r}"
                  for name, (actual, expected) in found.items() if actual != expected]
    if mismatches:
        raise PatchError(
            "Upstream package version changed; re-validate the patches in this script "
            "before bumping PythonRuntime/requirements.lock:\n  " + "\n  ".join(mismatches))


def edit_state(text: str, edit: Edit) -> str:
    """Return 'applied' or 'pending' for one edit, or 'unknown'."""
    anchors = text.count(edit.anchor)
    replacements = text.count(edit.replacement)
    # Insertion-style edits keep the anchor inside the replacement, so the
    # anchor legitimately still occurs once after they are applied.
    expected_anchors_when_applied = 1 if edit.anchor in edit.replacement else 0
    if replacements == 1 and anchors == expected_anchors_when_applied:
        return "applied"
    if replacements == 0 and anchors == 1:
        return "pending"
    return "unknown"


def patch_state(text: str, patch: Patch) -> str:
    """Return 'applied' or 'pending'; raise on anything in between."""
    states = [edit_state(text, edit) for edit in patch.edits]
    if all(state == "applied" for state in states):
        return "applied"
    if all(state == "pending" for state in states):
        return "pending"
    raise PatchError(
        f"{patch.path}: unexpected content for '{patch.name}' (edit states {states}). "
        "The upstream file changed or is partially patched; re-run ./scripts/bootstrap.sh "
        "after fixing the anchors in scripts/patch_python_runtime.py.")


def apply_patch(patch: Patch, check: bool) -> str:
    path = SITE_PACKAGES / patch.path
    text = read(path)
    state = patch_state(text, patch)
    if state == "applied":
        return "applied"
    if check:
        return "pending"
    for edit in patch.edits:
        text = text.replace(edit.anchor, edit.replacement, 1)
    if patch_state(text, patch) != "applied":
        raise PatchError(f"{patch.path}: patch '{patch.name}' did not apply cleanly")
    write_atomic(path, text)
    return "patched"


def hash_line_pattern(key: str) -> re.Pattern[str]:
    return re.compile(rf"^(\s*'{re.escape(key)}': ')([0-9a-f]{{128}})(',)$", re.M)


def sync_hashes(check: bool) -> str:
    """Rewrite the two core-script digests in _info.py from the patched files."""
    info_path = SITE_PACKAGES / VENDOR_INFO_FILE
    text = read(info_path)
    expected = {key: sha3_512(SITE_PACKAGES / path) for key, path in CORE_SCRIPTS.items()}

    current: dict[str, str] = {}
    for key in CORE_SCRIPTS:
        matches = hash_line_pattern(key).findall(text)
        if len(matches) != 1:
            raise PatchError(f"{VENDOR_INFO_FILE}: expected exactly one '{key}' entry, found {len(matches)}")
        current[key] = matches[0][1]

    up_to_date = current == expected and HASH_MARKER in text
    if up_to_date:
        return "applied"
    if check:
        if current == UPSTREAM_CORE_HASHES:
            return "pending (pristine upstream hashes)"
        return "pending"

    for key, digest in expected.items():
        text = hash_line_pattern(key).sub(lambda m, d=digest: f"{m.group(1)}{d}{m.group(3)}", text, count=1)
    if HASH_MARKER not in text:
        if HASH_MARKER_ANCHOR not in text:
            raise PatchError(f"{VENDOR_INFO_FILE}: header line not found; cannot place the patch marker")
        text = text.replace(HASH_MARKER_ANCHOR, HASH_MARKER_ANCHOR + HASH_MARKER, 1)
    write_atomic(info_path, text)
    return "patched"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify that every patch is applied; write nothing")
    args = parser.parse_args(argv)

    try:
        check_versions()
        results = [(patch.name, apply_patch(patch, args.check)) for patch in ALL_PATCHES]
        results.append((f"yt-dlp: sync core script digests in {VENDOR_INFO_FILE}", sync_hashes(args.check)))
    except PatchError as error:
        print(f"patch_python_runtime: {error}", file=sys.stderr)
        return 1

    for name, state in results:
        print(f"[{state}] {name}")
    if args.check and any(state != "applied" for _, state in results):
        print("patch_python_runtime: bundled packages are not fully patched. Run ./scripts/bootstrap.sh.",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
